### ISSUE TITLE
Error rendering HEIC on MacOS Ventura

### ISSUE THREAD

**Issue by ReessKennedy** [luxmargos/obsidian-image-magician-plugin#1]
I am excited about being able to possibly view HEIC in Obsidian so I installed this but I am getting the following error, even after closing and opening Obsidian again ... great idea on this! Hoping I can get it to go. 

<img width="572" alt="Screenshot 2024-05-02 at 1 09 32 PM" src="https://github.com/luxmargos/obsidian-image-magician-plugin/assets/3970267/5d86567a-c232-4d2d-af1a-968310245a64">

**Comment by luxmargos** [comment]
I have found that some HEIC files were rendered as broken, and this issue has been fixed in the next release, 1.0.9. Please update to this version and let me know if you encounter any further issues.
